branch-defaults:
  master:
    environment: flask-env
    group_suffix: null
environment-defaults:
  simple-santa-env:
    branch: null
    repository: null
global:
  application_name: simple-santa
  branch: null
  default_ec2_keyname: null
  default_platform: python-3.6
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
